dist: trusty
language: python
python:
  - '3.5'
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  - pip
install:
  - pip install -r requirements.txt
script:
  - cd test
  - ./run_tests.py
